services:
  aimock:
    build: ./aimock
    ports:
      - "8081:8081"
    restart: always
  
  frontend:
    build: ./annotator-fe
    ports:
      - "80:80"
    environment:
      SERVER_URL: http://backend:8080/api
    restart: always
    depends_on:
      backend:
        condition: service_healthy

  backend:
    build: ./annotator-be
    ports:
      - "8080:8080"
      - "8088:8088"
    restart: always
    volumes:
      - ./logs:/logs
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8088/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 10

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.2
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"

  kibana:
    image: docker.elastic.co/kibana/kibana:8.13.2
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

  logstash:
    image: docker.elastic.co/logstash/logstash:8.13.2
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
      - ./logs:/logs
    ports:
      - "5044:5044"
    depends_on:
      - elasticsearch