input {
  file {
    path => "/logs/events.log"
    start_position => "beginning"
    sincedb_path => "/dev/null"
  }
}

filter {

}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "my-app-logs"
  }
  stdout { codec => rubydebug }
}
