// eslint-disable-next-line @typescript-eslint/no-unused-vars
import React from 'react';
import Container from 'react-bootstrap/Container';
import Button from 'react-bootstrap/Button';
import { isUserLoggedIn } from '../../security/auth';
import { useNavigate } from 'react-router-dom';
import './homepage.css';


export default function HomePage() {
    /**
     * Hook to get the navigate function for programmatic navigation.
     */
    const navigate = useNavigate();


    return (
        <>
            <Container className="d-flex flex-column align-items-center text-center mt-5">
                    <h1 className="fw-bold">Welcome to Annotator</h1>
                    <p className="text-muted">Annotate data from a capacitive sensor!</p>

                    {!isUserLoggedIn() && (
                        <div className="mt-4 d-flex gap-3">
                            <Button variant="primary" size="lg" onClick={() => navigate('/user/login')}>
                                Login
                            </Button>
                            <Button variant="outline-primary" size="lg" onClick={() => navigate('/user/signup')}>
                                Sign Up
                            </Button>
                        </div>
                    )}

                    <div className="d-flex flex-wrap justify-content-center gap-3 mt-4 w-100">
                        <div
                            className="clickable-box"
                            onClick={() => navigate('/first-page')}
                        >
                            <h3>Download script!</h3>
                            <p>
                                Do you want to get into the action right away? Download python script to get started with annotating your data.
                            </p>
                        </div>
                        <div
                            className="clickable-box"
                            onClick={() => navigate('/second-page')}
                        >
                            <h3>Get more info</h3>
                            <p>
                                To start annotating just follow these few simple steps:
                            </p>
                            <ul>
                                <li>Be assigned to a team so you can access projects</li>
                                <li>Connect MGC3130 Hillstar Development Kit to your computer</li>
                                <li>Prepare camera so it can capture your hand above the sensor</li>
                                <li>Download the package with the annotating and test script</li>
                                <li>Make sure the example app can be run and you can see the data from sensor</li>
                                <li>Run the script for data capturing and follow instructions in its window</li>
                                <li>After you finish, proceed to the Projects page</li>
                                <li>Click the Add Project window and upload the zip file generated by the script</li>
                                <li>Choose the project from the list by clicking on it</li>
                                <li>Annotate data by dragging over them with left mouse pressed and chosen label</li>
                                <li>Use settings for creating new labels, changing image size and sending data to AI to train</li>
                            </ul>
                        </div>
                    </div>

            </Container>
        </>
    )
}
